server:
  port: 14001
  servlet:
    context-path: /cre

spring:
  application:
    name: cre
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cre?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456
#    initial-size: 30
#    max-active: 100
#    min-idle: 10
#    max-wait: 300
#    url: jdbc:mysql://120.55.192.186:3310/cre?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
#    username: root
#    password: 123456
#    initial-size: 30
#    max-active: 100
#    min-idle: 10
#    max-wait: 300
    url: jdbc:mysql://39.100.39.227:5186/cre?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: ywxz
    password: 2Un#oIuJTWseghUo
    initial-size: 30
    max-active: 100
    min-idle: 10
    max-wait: 300
  security:
    eureka-sport: 10001
    user:
      name: changsheng
      password: ZPgQhC2RJgXcruEtWd5acVNfkNgzq8O5

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${spring.security.eureka-sport}/eureka


mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wx:
  appId: wxceab92b2f5ad5fc8
  secret:
  cert:
  notifyUrl: http://app-api.changsh.net/cre/app/payment/callBack
  mchId: 1593862391
  mchKey:


swagger:
  enable: true

ftp:
  address: https://app-api.changsh.net
  server: localhost
  username:
  password: